Atualização 5-6-21/Programa Basileirão/jogos/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField, IntegerField
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired, ValidationError


class NovoJogoForm(FlaskForm):

    rodada = IntegerField('Rodada', validators=[DataRequired()])
    data = DateField('Data da Partida')
    vermelhos_mandante = IntegerField('Vermelhos', default=0)
    mandante = SelectField('Time Mandante', coerce=int)
    gols_mandante = IntegerField('Gols')
    amarelos_mandante = IntegerField('Amarelos', default=0)
    vermelhos_mandante = IntegerField('Vermelhos', default=0)
    visitante = SelectField('Time Visitante', coerce=int)
    gols_visitante = IntegerField('Gol')
    amarelos_visitante = IntegerField('Amarelos', default=0)
    vermelhos_visitante = IntegerField('Vermelhos', default=0)
    enviar = SubmitField('Enviar')

    def validate_visitante(self, visitante):
        if visitante.data == self.mandante.data:
            raise ValidationError('O Time mandante e o Visitante não podem'
                                  'ser o mesmo')

    def validate_rodada(self, rodada):
        if rodada.data > 22 or rodada.data < 0:
            raise ValidationError('Rodada Inválida')

Atualização 5-6-21/Programa Basileirão/jogos/__init__.py
from flask import Blueprint

bp = Blueprint('jogos', __name__, template_folder='./templates')

from jogos import routes

Atualização 5-6-21/Programa Basileirão/jogos/routes.py
from flask import render_template, redirect, url_for, flash, request
from flask_login import login_required
from jogos import bp
from jogos.forms import NovoJogoForm
from models import Jogo, Time
from brasileirao import db
from sqlalchemy.exc import IntegrityError


@bp.route('/')
@login_required
def index():
    jogos = Jogo.jogos_rodada()
    return render_template('listarjogos.html', title='Jogos', jogos=jogos)


@bp.route('/new', methods=['GET', 'POST'])
@login_required
def create():
    form = NovoJogoForm()
    times = list(Time.query.with_entities(Time.id, Time.nome))
    form.mandante.choices = times
    form.visitante.choices = times
    if form.validate_on_submit():
        jogo = Jogo(rodada=form.rodada.data, data=form.data.data,
                    time_mandante_id=form.mandante.data,
                    gols_mandante=form.gols_mandante.data,
                    amarelos_mandante=form.amarelos_mandante.data,
                    vermelhos_mandante=form.vermelhos_mandante.data,
                    time_visitante_id=form.visitante.data,
                    gols_visitante=form.gols_visitante.data,
                    amarelos_visitante=form.amarelos_visitante.data,
                    vermelhos_visitante=form.vermelhos_visitante.data)
        try:
            db.session.add(jogo)
            db.session.commit()
        except IntegrityError:
            db.session.rollback()
            e = {'Duplicidade': ["Esta partida já ocorrreu"]}
            return render_template('novojogo.html', title='Novo Jogo',
                                   form=form, jogo=None, errors=e)
        else:
            return redirect(url_for('jogos.index'))
    return render_template('novojogo.html', title='Novo Jogo', form=form,
                           jogo=None, errors=form.errors)


@bp.route('/<int:id>/edit', methods=['GET', 'POST'])
@login_required
def update(id):
    jogo = Jogo.query.get_or_404(id)
    form = NovoJogoForm()
    times = list(Time.query.with_entities(Time.id, Time.nome))
    form.mandante.choices = times
    form.visitante.choices = times
    if form.validate_on_submit():
        jogo.rodada = form.rodada.data
        jogo.data = form.data.data
        jogo.time_mandante_id = form.mandante.data
        jogo.gols_mandante = form.gols_mandante.data
        jogo.amarelos_mandante = form.amarelos_mandante.data
        jogo.vermelhos_mandante = form.vermelhos_mandante.data
        jogo.time_visitante_id = form.visitante.data
        jogo.gols_visitante = form.gols_visitante.data
        jogo.amarelos_visitante = form.amarelos_visitante.data
        jogo.vermelhos_visitante = form.vermelhos_visitante.data
        db.session.add(jogo)
        db.session.commit()
        flash('Suas alterações foram salvas.')
        return redirect(url_for('jogos.index'))
    elif request.method == 'GET':
        form.rodada.data = jogo.rodada
        form.data.data = jogo.data
        form.mandante.data = jogo.time_mandante_id
        form.gols_mandante.data = jogo.gols_mandante
        form.amarelos_mandante.data = jogo.amarelos_mandante
        form.vermelhos_mandante.data = jogo.vermelhos_mandante
        form.visitante.data = jogo.time_visitante_id
        form.gols_visitante.data = jogo.gols_visitante
        form.amarelos_visitante.data = jogo.amarelos_visitante
        form.vermelhos_visitante.data = jogo.vermelhos_visitante
    return render_template('novojogo.html', form=form, title="Editar Jogo",
                           jogo=jogo, errors=form.errors)


@bp.route('/<int:id>/delete')
@login_required
def delete(id):
    jogo = Jogo.query.get_or_404(id)
    db.session.delete(jogo)
    db.session.commit()
    return redirect(url_for('jogos.index'))

Atualização 5-6-21/Programa Basileirão/jogos/templates/listarjogos.html
{% extends "base.html"%}

{% block app_content %}
<body>
    <p><a style="background-color: rgb(66, 253, 9); color: rgb(10, 10, 10)  ; text-align: center;font-size: 30px" href="{{ url_for('jogos.create') }}">CRIAR PARTIDA</a></p>
    {% for rodada in jogos %}
    <h1 style="margin: 0px 0px 20px 0px; background-color: rgb(50, 47, 252);font-size: 80px; text-align: center"> RODADA {{ rodada }} </h1>
        <ul>
            {% for jogo in jogos [rodada] %}
            <div style="background-color: rgb(245, 240, 240);font-size: 20px; text-align: center ;">
            <li style="margin: 0px 0px 20px 0px;"> {{jogo.mandante.nome}} {{ jogo.gols_mandante }}  X  {{ jogo.gols_visitante }} {{jogo.visitante.nome}}
                <br>
                <br>
                <a href="{{ url_for('jogos.update', id=jogo.id) }}"> Editar </a>
                <br>
                <a href="{{ url_for('jogos.delete', id=jogo.id) }}"> Escluir </a> 
            </li>
            <div style="margin: 0px 0px 20px 0px;"> Data: {{ jogo.data }} </div></b></div>
            {% endfor %}
        </ul>
</body>
{% endblock %} 

Atualização 5-6-21/Programa Basileirão/jogos/templates/novojogo.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
<!-- Esse bloco é um gerenciamento de Erro, não precisa mexer -->
{% if errors %}
	<div class="container">
    	{%- for msg in errors %}
    		<div class="alert alert-danger" role="alert">
				{{ msg }}
				{% for error in errors[msg] %}
				{{error}}
				{% endfor %}
			</div>
    	{% endfor -%}
	</div>
{% endif %}
<!-- Faça o template a partir daqui-->
<b><body>
<form method="POST" action="">
	{{ form.hidden_tag() }}
	<div style="background-color: rgb(255, 255, 255);">
<div style="margin: 250px auto 0px 320px;">
	{{ form.data.label() }} 
	<a style="color: black;">{{ form.data() }}</a> 
</div>
<div style="margin: 20px auto 0px 320px; color: black;">
	{{ form.mandante() }} {{ form.gols_mandante(size=3)}} X {{ form.gols_visitante(size=3)}} {{ form.visitante() }}
</div>
<div style="margin: 20px auto 0px 320px;">
	{{ form.rodada.label }} 
	<a style="color: black;">{{ form.rodada() }}</a>
</div>
<div style="margin: 20px auto 0px 320px;">
	Cartões amarelos para o mandante:
	<a style="color: black;">{{ form.amarelos_mandante }}</a>
</div>
<div style="margin: 20px auto 0px 320px;">
	Cartões amarelos para o visitante:
	<a style="color: black;">{{ form.amarelos_visitante }}</a>
</div>
<div style="margin: 20px auto 0px 320px;">
	Cartões vermelhos para o mandante:
	<a style="color: black;">{{ form.vermelhos_mandante }}</a>
</div>
<div style="margin: 20px auto 0px 320px;">
	Cartões vermelhos para o visitante:
	<a style="color: black;">{{ form.vermelhos_visitante }}</a>
</div>
<b><div style="margin: 5px auto 0px 320px; color: black;">
    {{ form.enviar() }}</b>
</div>
</div>
</body></b>
{% endblock %}